/**
 * The official 77 provinces of Thailand (จังหวัด), bare names with no "จ."
 * prefix. Client-safe (no Prisma / Node-only imports). Used by the alumni-agency
 * in-country form's จังหวัด `<datalist>` (mirrors the ประเทศ datalist pattern).
 *
 * The list is typeable autocomplete, not a strict enum — a user may still enter
 * a value not in this set. The required-ness is enforced separately in the
 * zod schemas (lib/validations/alumni-agency.ts) via `isThailandCountry`.
 */
export const THAI_PROVINCES: readonly string[] = [
  // Northern (17)
  "เชียงราย",
  "เชียงใหม่",
  "น่าน",
  "พะเยา",
  "แพร่",
  "แม่ฮ่องสอน",
  "ลำปาง",
  "ลำพูน",
  "อุตรดิตถ์",
  "ตาก",
  "สุโขทัย",
  "พิษณุโลก",
  "เพชรบูรณ์",
  "พิจิตร",
  "กำแพงเพชร",
  "นครสวรรค์",
  "อุทัยธานี",
  // Northeastern / Isan (20)
  "อุดรธานี",
  "หนองบัวลำภู",
  "หนองคาย",
  "บึงกาฬ",
  "เลย",
  "สกลนคร",
  "นครพนม",
  "มุกดาหาร",
  "ชัยภูมิ",
  "ขอนแก่น",
  "กาฬสินธุ์",
  "มหาสารคาม",
  "ร้อยเอ็ด",
  "ยโสธร",
  "อำนาจเจริญ",
  "อุบลราชธานี",
  "ศรีสะเกษ",
  "สุรินทร์",
  "บุรีรัมย์",
  "นครราชสีมา",
  // Central / East / West (26, incl. Bangkok)
  "กรุงเทพมหานคร",
  "กาญจนบุรี",
  "ชัยนาท",
  "นครนายก",
  "นครปฐม",
  "นนทบุรี",
  "ปทุมธานี",
  "พระนครศรีอยุธยา",
  "อ่างทอง",
  "ลพบุรี",
  "สิงห์บุรี",
  "สระบุรี",
  "สุพรรณบุรี",
  "สมุทรปราการ",
  "สมุทรสาคร",
  "สมุทรสงคราม",
  "เพชรบุรี",
  "ประจวบคีรีขันธ์",
  "ราชบุรี",
  "ชลบุรี",
  "ระยอง",
  "จันทบุรี",
  "ตราด",
  "ฉะเชิงเทรา",
  "ปราจีนบุรี",
  "สระแก้ว",
  // Southern (14)
  "ชุมพร",
  "ระนอง",
  "สุราษฎร์ธานี",
  "นครศรีธรรมราช",
  "ภูเก็ต",
  "กระบี่",
  "พังงา",
  "ตรัง",
  "พัทลุง",
  "สตูล",
  "สงขลา",
  "ปัตตานี",
  "ยะลา",
  "นราธิวาส",
] as const;
